# Generated by Django 5.2.6 on 2025-12-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('fathers_name', models.CharField(blank=True, max_length=30, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('enrollment_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_images/')),
            ],
        ),
    ]
